In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-reg/sample_submission.csv
/kaggle/input/digit-reg/train.csv
/kaggle/input/digit-reg/test.csv


In [2]:
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers,models

In [3]:
train = pd.read_csv("../input/digit-reg/train.csv")
X_test = pd.read_csv('../input/digit-reg/test.csv')

In [4]:
train

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [5]:
y_train = train['label']
X_train = train.drop(columns=['label'])

In [6]:
y_train = np.array(y_train)
y_train

array([1, 0, 1, ..., 7, 6, 9])

In [7]:
X_train.shape

(42000, 784)

In [8]:
X_test = X_test.to_numpy()

In [9]:
X_train = X_train.to_numpy()

In [10]:
X_test[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  10,  17,  17,  17,  17,  81, 180, 180,
        35,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 139, 253, 253, 253, 253, 253,
       253, 253,  48,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,  60, 228, 253, 25

In [11]:
X_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 188, 255,  94,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 191, 250, 253,  93,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [12]:
X_train.shape

(42000, 784)

In [13]:
X_train = X_train/255

In [14]:
X_test = X_test/255

In [15]:
model = keras.Sequential([
      keras.layers.Dense(10,input_shape=(X_train.shape[1],),activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train,y_train,epochs=20)

2022-07-22 03:49:42.036067: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-07-22 03:49:42.448010: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/20
1313/1313 [==============================] - 3s 2ms/step - loss: 0.5123 - accuracy: 0.8698
Epoch 2/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.3138 - accuracy: 0.9131
Epoch 3/20
1313/1313 [==============================] - 3s 2ms/step - loss: 0.2867 - accuracy: 0.9194
Epoch 4/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2735 - accuracy: 0.9233
Epoch 5/20
1313/1313 [==============================] - 3s 2ms/step - loss: 0.2654 - accuracy: 0.9256
Epoch 6/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2586 - accuracy: 0.9278
Epoch 7/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2541 - accuracy: 0.9286
Epoch 8/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2495 - accuracy: 0.9295
Epoch 9/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2470 - accuracy: 0.9296
Epoch 10/20
1313/1313 [==============================] - 2s 2ms/step - loss: 0.243

In [16]:
y_pred = model.predict(X_test)

In [17]:
y_pred = [np.argmax(i) for i in y_pred]
y_pred[:5]

[2, 0, 9, 7, 3]

In [18]:
col = pd.read_csv('../input/digit-reg/sample_submission.csv')
cols = col['ImageId']

In [19]:
data = pd.concat([pd.Series(cols,name='ImageId'),pd.Series(y_pred)],axis=1)
data

ImageId  0
0            1  2
1            2  0
2            3  9
3            4  7
4            5  3
...        ... ..
27995    27996  9
27996    27997  7
27997    27998  3
27998    27999  9
27999    28000  2

[28000 rows x 2 columns]

In [20]:
data.to_csv('submission.csv',index=False)